---
sidebar: sidebar 
permalink: administer/upgrades-aide-summary.html 
keywords: update, firmware, system files, automatic updates, ai data engine, aide 
summary: Lernen Sie die verschiedenen Komponenten eines AI Data Engine Systems kennen, die auf dem neuesten Stand gehalten werden müssen. 
---
= AI Data Engine systemaktualisierungen und Kompatibilität
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Halten Sie die AI Data Engine (AIDE) Systemkomponenten auf dem neuesten Stand, um optimale Leistung und Zugriff auf neue Funktionen zu gewährleisten. Aktualisieren Sie die Komponenten nach der Bereitstellung, wenn neue Software oder Firmware verfügbar ist, wenn Sie Knoten hinzufügen oder ersetzen, oder regelmäßig für Funktionsupdates.



== AIDE Systemkomponenten

Es gibt zwei Hauptkomponenten, die in einem AIDE System aktualisiert werden müssen: ONTAP software und AIDE software, zu der auch DCN firmware gehört.



=== ONTAP Software

ONTAP ist das Betriebssystem, das auf NetApp Speicher­systemen, einschließlich der in AIDE Deployments verwendeten, läuft. Halten Sie ONTAP aktuell, um die Systemstabilität, Sicherheit und Kompatibilität mit AIDE Komponenten zu erhalten. AIDE Komponenten werden separat aktualisiert.



=== AIDE Software-Updates

AIDE Console software und DCN Firmware-Updates werden zusammen als ein einziges Paket (.tgz) verteilt und sind nicht in ONTAP Images eingebettet. Updates gewährleisten die ordnungsgemäße Funktion der Hardwarekomponenten innerhalb des AIDE Systems und bieten neue Funktionen, Leistungsverbesserungen und Fehlerbehebungen.



== Den Aktualisierungsprozess verstehen

AIDE software updates können über ONTAP System Manager verwaltet werden.

AIDE unterstützt die automatische Software-Update-Funktionalität von ONTAP nicht. Sie können sich für Benachrichtigungen von link:https://mysupport.netapp.com/site/downloads["NetApp Support Site Downloads"^] anmelden, aber alle Updates der AIDE software werden manuell vom Administrator durchgeführt.

Veröffentlichungsarten und -umfang:

* ONTAP Hauptversionen (9.x.x) und AIDE Hauptversionen (9.x.x U0) führen neue Funktionen, APIs oder Änderungen ein, die die ONTAP Integration betreffen.
* ONTAP patch releases (9.x.x Px) und AIDE update releases (9.x.x Ux) enthalten Korrekturen und Aktualisierungen, die die ONTAP Integration nicht beeinträchtigen.




== Kompatibilitätsmatrix

Stellen Sie die Kompatibilität zwischen ONTAP und AIDE software sicher, wenn Sie Updates planen.

AIDE software wird als "U"-Releases veröffentlicht. Ein AIDE Major Release ist ein "U0"-Release und nachfolgende Minor Releases werden "U1" und später sein.



=== ONTAP und AIDE Kompatibilität

[cols="1,1"]
|===
| AIDE Releases | Unterstützte ONTAP Versionen 


| 9.18.1 U0 | 9.18.1 GA und alle 9.18.1 Px 


| 9.18.1 U1 und später | 9.18.1 GA und alle 9.18.1 Px 
|===
[NOTE]
====
„Px“ bezeichnet alle ONTAP Patch-Releases in der Hauptversion (zum Beispiel 9.18.1 P1, 9.18.2 und andere).

====


=== AIDE Upgrade-Pfade

Die folgenden Beispiele verwenden hypothetische zukünftige Versionen, um die zulässigen Upgrade- und Update-Pfade ab AIDE 9.18.1 U0 und 9.18.1 U1 zu zeigen.

[cols="25,25,50"]
|===
| Wenn Ihre aktuelle AIDE Release ist… | Und Ihre angestrebte AIDE release ist… | Ihr Upgrade- oder Updatepfad ist… 


| 9.18.1 U0 | 9.18.1 U1 | Direkt 


| 9.18.1 U0 | 9.18.1 U3 | Direkt (Sie können von jeder Ux auf jede spätere Ux in 9.18.1 aktualisieren) 


| 9.18.1 U1 | 9.18.1 U3 | Direkt (Sie können von jeder Ux auf jede spätere Ux in 9.18.1 aktualisieren) 
|===


== Einschränkungen rückgängig machen

AIDE-Systeme unterstützen keine Rücksetzvorgänge für DCN-Firmware, AIDE-Software-Updates oder ONTAP auf AFX-Speichersystemen. Nachdem Sie ein Update oder Upgrade installiert haben, können Sie nicht zu einer vorherigen Version zurückkehren. Überprüfen Sie <<Kompatibilitätsmatrix,Kompatibilitätsanforderungen>> vor dem Update oder Upgrade.

.Verwandte Informationen
* https://docs.netapp.com/us-en/ontap-afx/administer/upgrade-ontap.html["ONTAP-Software für AFX-Systeme aktualisieren"^]
* link:update-aide-firmware-software.html["AIDE-Software aktualisieren"]

